### ISSUE TITLE
Loading a file on url

### ISSUE THREAD

**Issue by kaspar-allenbach** [steampixel/simplePHPRouter#1]
Hi.

I'm trying to get my head around your php Router.

I want to load the file `/wetter.php` when having the url `domain.com/cityX/wetter`.

So I write in `index.php` what exactely?

```
Route::add('/(.*)/wetter.php',function(){
  echo 'das wäre die wetterseitewetterseite';
});
```
I'll then a d a test link `<a href ="/cityX/wetter">Test</a>`

But this doesn't work `The requested URL /cityX/wetter.php was not found on this server.`. What do I miss?

**Comment by steampixel** [comment]
Hi,

i dont think this is a issue. The router does not load any php files by default. It just executes the anonymous function. You also have to remove the .php from your regexp to match the route without the ending. Howewer. You could implement this by doing:

```
// Define weather route
Route::add('/(.*)/wetter',function($cityname){
  // The code inside this block gets only executed if this route is matched
  echo 'das wäre die wetterseitewetterseite von '.$cityname;
  // Include a custom file
  // The $cityname - variable should be available in wetter.php too
  include('wetter.php');
});
```

By the way: If a route was not found the router should execute the 404-route. This means something could be wrong with your .htaccess configuration. You should never see something like "The requested URL /cityX/wetter.php was not found on this server" if everything is configured correctly. Because every request will lead to index.php. Check your .htaccess and make sure mod_rewrite module is loaded in apache webserver. If you do not use apache you have to create the rewrite rule for the router by yourself.
