### ISSUE TITLE
BasePath not working

### ISSUE THREAD

**Issue by c0depwn** [steampixel/simplePHPRouter#3]
I have the project in a subfolder and I changed the Route::run('/'); to Route::run('/myfolder'); and I also
changed the RewriteBase from / to /myfolder but its not working for me somehow... 
Hope you can help thanks!

**Comment by steampixel** [comment]
Hey! I have made a test using Vagrant with Apache2 and PHP 5.6 on ubuntu/trusty64. But everything works fine for me. I have added my testfiles to this repo. Take a look at the bootstrap.sh file. There you will find my current server configuration.

This is my basepath in .htaccess: 
```
# set your rewrite base
# Edit this in your init method too if you script lives in a subfolder
RewriteBase /myfolder
```

This is my run() call:
```
// Run the Router with the given Basepath
// If your script lives in the web root folder use a / or leave it empty
Route::run('/myfolder');
```

In order to run the test correctly inside a basepath you should adjust the navigation links:
```
  <li><a href="">home</a></li>
  <li><a href="/myfolder/index.php">index.php</a></li>
  <li><a href="/myfolder/user/3/edit">edit user 3</a></li>
  <li><a href="/myfolder/foo/5/bar">foo 5 bar</a></li>
  <li><a href="/myfolder/foo/bar/foo/bar">long route example</a></li>
  <li><a href="/myfolder/contact-form">contact form</a></li>
  <li><a href="/myfolder/test.html">test.html</a></li>
  <li><a href="/myfolder/this-route-is-not-defined">404 Test</a></li>
  <li><a href="/myfolder/this-route-is-defined">405 Test</a></li>
```

Can you please explain what exactly happens if you navigate to /myfolder? Do you see an error? Do you see a blank page or something else?

**Comment by c0depwn** [comment]
Thank you so much for your quick response and time!
I feel pretty dumb right now I noticed I forgot to adjust the navigation links xD...
