### ISSUE TITLE
how to add basic authenticator?

### ISSUE THREAD

**Issue by lsjack93** [steampixel/simplePHPRouter#36]
Hello, I am trying to implement basic authentication, but without success yet. Have you planned something similar?

**Comment by steampixel** [comment]
Hi @lsjack93,

basic auth is not part of the router. This is an extra topic. I will not plan to add this to the router because this is has nothing to do with basic routing. You can use PHP to add basic auth before the routers run() method is called or you can add those logic inside single routes. Examples can be found here: https://www.php.net/manual/de/features.http-auth.php

If you are on Apache you can also use .htaccess basic auth to protect the whole app: https://homepage-kosten.de/htaccess/
