### ISSUE TITLE
Missing js/css files while using double routes

### ISSUE THREAD

**Issue by flamurbeqiraj** [steampixel/simplePHPRouter#40]
Hello,
In my web project I have in the file javascripts.php all js plugins stored same as css.php for the styles. When I use this code:
`Route::add('/product/([0-9]*)/edit', function($id) {
        require_once('product.php');
}, 'get');`
The browser is looking up to the non existing folder '/product/js/owl.carousel.js'.
But indeed there is no folder called '/product/'. The real path is just '/js/owl.carousel.js'.
The same problem is happening to all included files.

**Comment by steampixel** [comment]
Hey,
this is the expected behavior. Please use absolute paths to include your CSS and JS files. Most CMS Systems will provide some kind of a variable or a function that generates the absolute part (eg. https://mywebsite.com/) of the URL. The browser does not know that the path is just virtual. If your project is not installed within a subfolder you could also use domain relative pathes. So you could use `/js/owl.carousel.js` instead of `js/owl.carousel.js`.

**Comment by steampixel** [comment]
Tip: Use the `define('BASEPATH','/');` constant defined in line 10 of the example.php. You will notice that this constant is used to prepend the navigation links. This is the same as includind CSS and JS files. Just prepend your script and style tag attributes the same way.

**Comment by flamurbeqiraj** [comment]
Ahhh, Okay. Allright this wasn't really an Issue than. Thank you.
