### ISSUE TITLE
Not working for php5.2

### ISSUE THREAD

**Issue by on3ss** [steampixel/simplePHPRouter#41]
I'm calling the route class as follows
```
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
require('./src/Route/Route.php');
Route::run('/ebilling-eis');

Route::add('/', function(){
	print('Welcome');
});

Route::add('/test', function(){
	print('Welcome Test');
});
```
when i go to both of these routes, a blank screen shows up without the printed string

**Comment by steampixel** [comment]
Hey @on3ss ,
please try to call the `Route::run('/ebilling-eis');` method at the end of your script.
You should first register the routes with `Route::add`. And then you can run them. This script is synchon. If you define the routes after the ::run they will just be ignored because the router has already finished the job.

**Comment by on3ss** [comment]
I've already tried what you're suggesting but no dice.

**Comment by steampixel** [comment]
PHP 5.2 is from 2006. And PHP 8 is coming closer. I would recommend updating your system.

**Comment by on3ss** [comment]
Unfortunately that's not up to me. Thanks anyway.

**Comment by steampixel** [comment]
Unfortunately, anonymous functions, the core principle of the router, are only supported from version 5.3 :-(
