### ISSUE TITLE
Can't access data in GET query

### ISSUE THREAD

**Issue by ay0ks** [steampixel/simplePHPRouter#47]
Hello, while trying to do
```php
Route::add('/greet?([a-z]*)', function ($who) use($pug)
{
    echo $pug->renderFile('index.pug', [
        'title' => 'Hello ' . $who,
    ]);
});
```
I get only rendered 'Hello'
URL: `/greet?World`

**Comment by steampixel** [comment]
Hi @ay0ks,
I think the problem is the ? sign inside your pattern. This is nothing about this router. Its about PHP basics. You try to parse out a query string using the router. But the problem is that the query parsing is already finished by the web server or PHP at an early stage of runtime before your code gets executed. All the router sees is that you are on the path '/greet'. Everything behind the ? was cut away by the web server or by PHP before the router fires. This is normal PHP behavior. You have two options:

1. Use the router to parse the string but don't use ?. For example use a virtual sub folder:
```
Route::add('/greet/([a-z]*)', function ($who) use($pug)
{
    echo $pug->renderFile('index.pug', [
        'title' => 'Hello ' . $who,
    ]);
});
```
2. Use the global PHP $_GET Array to access your query values. There you will find everything defined after your ? inside the URL:
```
Route::add('/greet)', function () use($pug)
{
    echo $pug->renderFile('index.pug', [
        'title' => 'Hello ' . $_GET['who'],
    ]);
});
```
This works with this URL: /greet?who=world

Note: Its not recommended to use a variable key like /greet?world because the first word should be a fixed key. You could use a dynamic key but this is not recommended in my opinion:
```
Route::add('/greet)', function () use($pug)
{
    $query_keys = array_keys($_GET);
    echo $pug->renderFile('index.pug', [
        'title' => 'Hello ' . $query_keys[0]
    ]);
});
```
