### ISSUE TITLE
File protection from direct access

### ISSUE THREAD

**Issue by flamurbeqiraj** [steampixel/simplePHPRouter#55]
Hello dev.

I love using your script, im was and still am curious on how to prevent the direct access on let's say: about.php.
I am loding this page via '/about', but anytime i type the extension also, the same result view pops up!

It would be awesome if I could somehow prevent the direct access of the files, and make them accessable only via the routing system.

Best regards.

**Comment by hsjang95** [comment]
Try like below
Inspect extension in url and redirect page

$searchName = ".php";
$request_uri = $_SERVER['REQUEST_URI'];
if(strpos($request_uri, $searchName) !== false) {  
  header('Location: /home');
}

**Comment by steampixel** [comment]
Hey,
this is a Apache configuration and / or a design flaw or your software.

1. Why the about.php is delivered directly? Open the .htaccess file. It configures the Apache behavior configuration. There you will find this line: "RewriteCond %{REQUEST_FILENAME} !-f" This line tells Apache not to call the index.php file if the file was found in the filesystem. Instead the found file will be responded directly to your browser. This is important for images and css or js files for example. Because you don't want to have them progressed by your PHP-Router. You could now create another rule that would exclude all requests with a .php extension from this behavior. But there is another way.

2. You should never put include files directly into your web root. Just copy it away from there. If you can put them one folder above. So they are completely invisible to direct web access but you can still include them by using include ('../includes') for example. Or put them into a separate include folder inside your web root and protect this folder with an extra .htaccess file.

**Comment by flamuraxians** [comment]
Im using allready another ppproach, please let me know if this is also a good solution:

index.php
`define("isSafe", true);`

about.php
`defined("isSafe") or die("This page is not accessable!");`

What I basicly did here is that I have defined a key "isSave" which is set to the first lines (NOT INSIDE OF ANY ROUTE). And visitors should be able to visit the pages only throught index.php

Please let me know if this is somehow risky. if yes tell me any reason! Thank you....

**Comment by steampixel** [comment]
This is also a working solution. The only "risk" with this approach is that you have to keep this in mind. I think this pattern is more hidden for your future self and other developers. There is the risk that you forget this line in some files. But I think some popular CMS systems use a similar strategy (Typo3, etc...).

Another thing is that this files can easily found by brute forcing the web server (fuzzing). If I request the about.php the web server will response with an 200 status code. So i can know if there is a file. Even if this file will do nothing its pure existence can lead to the structure of your code and files.

**Comment by steampixel** [comment]
But your approach could be a second step of security hardening. Combine it for example with a protected includes directory.

**Comment by flamuraxians** [comment]
Maybe I can write also a code to send a response code of 404 not found, when hitting the page direct when the key is not defined? What about that?

**Comment by steampixel** [comment]
That would be really confusing for web fuzzer :-)

**Comment by flamuraxians** [comment]
Okay thank you for the time and contribute :).
