### ISSUE TITLE
Question: How to disable automatic file redirect

### ISSUE THREAD

**Issue by laurenskok** [steampixel/simplePHPRouter#6]
Hello @SteamPixel

In fact what I want to do is the following: 
Use you router to include my header / footer / sidebar files automatically without including them on every page. For this it is crucial that every URL request passes to the index and get the right route path that is configured. 

Sadly somehow this is not working when I just remove your HTACCESS rewriteConditions. 

Could you provide some explanations here?

**Comment by steampixel** [comment]
Hi,

I hope I understand your problem :-) Could you provide a code example please?

I think you need a basic concept for themes, layouts and pages. This is not part of this router. You can see this problem in action by looking at the index.php file. There is a navi() function that gets called from every single route. So the navi will be displayed on every page.

I think this is a similar problem. Instead of calling nav(), footer(), header(), sidebar(), etc... in every callback function you should consider calling something like this:

`
Route::add('/',function(){
  Page::render('home');
});
`
I have another project on GitHub I am working currently on. Checkout https://github.com/steampixel/simplePHPPages

This will give you an overview how you can render different pages with the same layout. It utilyzes the same router class. Its not very well documented at the moment. But its simple and basic. I think you will understand the source.

**Comment by laurenskok** [comment]
Hi Steampixel, 

Thank you for your explanation! I will certainly check out your other project. For now, we just resolved the issue by putting all our pages in a 'view' directory, in this way the path is never triggered automatically. And by using functions with parameters we trigger the right header/footer like you did with the navi function. 

We will upgrade once we have the skeleton ready, thank you again for your time to look at this issue. 

Regards
Laurens
